[platformio]
default_envs = waveshare_esp32s3_touch_amoled_216

[env:waveshare_esp32s3_touch_amoled_216]
platform = espressif32
board = waveshare_esp32s3_touch_amoled_216
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags =
  -D CORE_DEBUG_LEVEL=0

board_build.embed_files =
  assets/fish.jpg
  assets/fish_small.jpg

lib_deps =
  bitbank2/JPEGDEC@^1.8.4
