[platformio]
default_envs = waveshare_esp32s3_touch_amoled_216

[env:waveshare_esp32s3_touch_amoled_216]
platform = espressif32
board = waveshare_esp32s3_touch_amoled_216
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags =
  -D CORE_DEBUG_LEVEL=0

board_build.embed_files =
  assets/fish_1_u.png
  assets/fish_2_u.png
  assets/fish_3_u.png
  assets/fish_4_u.png
  assets/fish_5_u.png
  assets/fish_6_u.png
  assets/fish_7_u.png
  assets/fish_8_u.png
  assets/fish_9_u.png
  assets/fish_10_u.png
  assets/fish_11_u.png
  assets/fish_12_u.png
  assets/bubble_1.png
  assets/bubble_2.png
  assets/bubble_3.png
  assets/bubble_4.png
  assets/bubble_5.png
  assets/bubble_6.png
  assets/bubble_7.png
  assets/bubble_8.png

lib_deps =
  bitbank2/PNGdec@^1.1.4
  lewisxhe/SensorLib@^0.3.1
